In [1]:
import pandas as pd 
import re
import os
import yaml
from pathlib import Path
import ast

Create some Directory to be used

In [2]:
cleaned_dir = Path("PROCESSED")

cleaned_dir.mkdir(parents = True, exist_ok = True)

Load the Dataset Using Pandas

In [3]:
with open("dataconf.yml", "r") as f:
    config = yaml.safe_load(f)
file_path = os.path.join(config["data_path"], "dum_data.xlsx")

#print(f"File path: {file_path}")

In [4]:
file_path = Path("basedata/dumm_data.xlsx").resolve()
df = pd.read_excel(file_path, skiprows = 0)

In [5]:
df.head(25)

,Timestamp,Datetime,Procada Current,Procada Voltage,Laser Power,Wire Current,Wire Speed,Wire Voltage,Unnamed: 8,X,Y,Z,<- Robot pos
0,1.704451e+09,2024-01-05 10:34:52.162,"{'SetVal': 0.0, 'v': 0.2871}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-482.449829,-14.914701,151.575500,NaN
1,1.704451e+09,2024-01-05 10:34:52.195,"{'SetVal': 0.0, 'v': 0.2871}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-482.263367,-19.762871,151.791931,NaN
2,1.704451e+09,2024-01-05 10:34:52.229,"{'SetVal': 0.0, 'v': 0.2871}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-483.006927,-16.474230,151.901566,NaN
3,1.704451e+09,2024-01-05 10:34:52.262,"{'SetVal': 0.0, 'v': 0.2871}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-480.737061,-17.901360,135.418030,NaN
4,1.704451e+09,2024-01-05 10:34:52.295,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-480.826111,-16.183176,135.999893,NaN
5,1.704451e+09,2024-01-05 10:34:52.329,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-483.828003,-18.554438,152.221420,NaN
6,1.704451e+09,2024-01-05 10:34:52.362,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-480.990173,-16.998444,136.692535,NaN
7,1.704451e+09,2024-01-05 10:34:52.395,"{'SetVal': 0.0, 'v': 0.2802}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-484.385254,-14.036122,151.920593,NaN
8,1.704451e+09,2024-01-05 10:34:52.429,"{'SetVal': 0.0, 'v': 0.2802}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-485.242981,-16.541672,151.891312,NaN
9,1.704451e+09,2024-01-05 10:34:52.462,"{'SetVal': 0.0, 'v': 0.2802}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-483.984833,-14.099407,151.901077,NaN
10,1.704451e+09,2024-01-05 10:34:52.495,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-479.424774,-21.173449,149.269501,NaN
11,1.704451e+09,2024-01-05 10:34:52.529,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-481.546997,-18.046221,151.370453,NaN
12,1.704451e+09,2024-01-05 10:34:52.562,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-483.915009,-19.956011,152.183334,NaN
13,1.704451e+09,2024-01-05 10:34:52.595,"{'SetVal': 0.0, 'v': 0.2867}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-480.787933,-16.007488,150.681900,NaN
14,1.704451e+09,2024-01-05 10:34:52.629,"{'SetVal': 0.0, 'v': 0.2867}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-479.334717,-19.394783,148.832230,NaN
15,1.704451e+09,2024-01-05 10:34:52.662,"{'SetVal': 0.0, 'v': 0.2867}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-479.178955,-20.841766,148.878937,NaN
16,1.704451e+09,2024-01-05 10:34:52.695,"{'SetVal': 0.0, 'v': 0.2894}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-482.697876,-8.916419,151.036179,NaN
17,1.704451e+09,2024-01-05 10:34:52.729,"{'SetVal': 0.0, 'v': 0.2894}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-480.949860,-12.984543,150.112503,NaN
18,1.704451e+09,2024-01-05 10:34:52.762,"{'SetVal': 0.0, 'v': 0.2894}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-483.362823,-11.172759,151.537140,NaN
19,1.704451e+09,2024-01-05 10:34:52.795,"{'SetVal': 0.0, 'v': 0.2801}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-483.026581,-13.407113,151.657059,NaN
20,1.704451e+09,2024-01-05 10:34:52.829,"{'SetVal': 0.0, 'v': 0.2801}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-481.483887,-10.652870,150.282669,NaN
21,1.704451e+09,2024-01-05 10:34:52.862,"{'SetVal': 0.0, 'v': 0.2801}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-484.352753,-7.387171,151.320786,NaN
22,1.704451e+09,2024-01-05 10:34:52.895,"{'SetVal': 0.0, 'v': 0.2868}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-485.295135,-9.531982,151.330246,NaN
23,1.704451e+09,2024-01-05 10:34:52.929,"{'SetVal': 0.0, 'v': 0.2868}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-480.614899,-8.478767,148.847656,NaN
24,1.704451e+09,2024-01-05 10:34:52.962,"{'SetVal': 0.0, 'v': 0.2868}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",NaN,-479.977631,-12.271223,148.758133,NaN

`Cleaning Process`

In [6]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace("<- Robot pos", "")     # Remove the "<- Robot pos"


df = df.iloc[:, :-1]

In [7]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='s')

In [8]:
df = df.drop(columns=[col for col in df.columns if 'Unnamed' in col or 'empty' in col.lower()])

In [9]:
df.head(10)

,Timestamp,Datetime,Procada Current,Procada Voltage,Laser Power,Wire Current,Wire Speed,Wire Voltage,X,Y,Z
0,2024-01-05 10:34:52.161999941,2024-01-05 10:34:52.162,"{'SetVal': 0.0, 'v': 0.2871}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-482.449829,-14.914701,151.575500
1,2024-01-05 10:34:52.195333004,2024-01-05 10:34:52.195,"{'SetVal': 0.0, 'v': 0.2871}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-482.263367,-19.762871,151.791931
2,2024-01-05 10:34:52.228667021,2024-01-05 10:34:52.229,"{'SetVal': 0.0, 'v': 0.2871}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-483.006927,-16.474230,151.901566
3,2024-01-05 10:34:52.262000084,2024-01-05 10:34:52.262,"{'SetVal': 0.0, 'v': 0.2871}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-480.737061,-17.901360,135.418030
4,2024-01-05 10:34:52.295332909,2024-01-05 10:34:52.295,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-480.826111,-16.183176,135.999893
5,2024-01-05 10:34:52.328666925,2024-01-05 10:34:52.329,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-483.828003,-18.554438,152.221420
6,2024-01-05 10:34:52.361999989,2024-01-05 10:34:52.362,"{'SetVal': 0.0, 'v': 0.2893}","{'SetVal': 0.0, 'v': 0.0002}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-480.990173,-16.998444,136.692535
7,2024-01-05 10:34:52.395333052,2024-01-05 10:34:52.395,"{'SetVal': 0.0, 'v': 0.2802}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-484.385254,-14.036122,151.920593
8,2024-01-05 10:34:52.428667068,2024-01-05 10:34:52.429,"{'SetVal': 0.0, 'v': 0.2802}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-485.242981,-16.541672,151.891312
9,2024-01-05 10:34:52.461999893,2024-01-05 10:34:52.462,"{'SetVal': 0.0, 'v': 0.2802}","{'SetVal': 0.0, 'v': 0.0001}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 0.0, 'v': 0.0}","{'SetVal': 5.0, 'v': 5.0}","{'SetVal': 0.0, 'v': 0.0}",-483.984833,-14.099407,151.901077

Extract Numeric values from the SetVal strings.

In [10]:
def extract_numvalue(value):
    """_summary_
    Convert the string representation of dictionary to actual dictionary
    First, replace single quotes with double quotes for proper JSON format

    Returns:
        float: Value of each measured quatities in the data (the 'v' value from the dictionary)
    """
    
    if isinstance(value, str):
        if "SetVal" in value:
            try:
                value_dict = ast.literal_eval(value)

                return float(value_dict['v'])
            except (ValueError, SyntaxError, KeyError):
                # Fallback to regex if the above method fails
                match = re.search(r"'v': '?([-\d.]+)'?", value)
                if match:
                    return float(match.group(1))
        try:
            return float(value)
        except ValueError:
            return value
    return value

Apply the Cleaning to all columns except DateTime

In [11]:
numeric_columns = df.columns.difference(["Datetime", "Timestamp"])
for col in numeric_columns:
    df[col] = df[col].apply(extract_numvalue)

Convert the Datatime to proper datatime format.

In [12]:
df['Datetime'] = pd.to_datetime(df["Datetime"])

In [13]:
df = df.dropna(how = "all")

#Reset the index.
df = df.reset_index(drop = True)

Check for missing values.

In [14]:
print(f"Missing values: \n {df.isnull().sum()}")

Missing values:
 Timestamp          0
Datetime           0
Procada Current    0
Procada Voltage    0
Laser Power        0
Wire Current       0
Wire Speed         0
Wire Voltage       0
X                  0
Y                  0
Z                  0
dtype: int64

In [15]:
df.head(50)

,Timestamp,Datetime,Procada Current,Procada Voltage,Laser Power,Wire Current,Wire Speed,Wire Voltage,X,Y,Z
0,2024-01-05 10:34:52.161999941,2024-01-05 10:34:52.162,0.2871,0.0001,0.0,0.0,5.00,0.00,-482.449829,-14.914701,151.575500
1,2024-01-05 10:34:52.195333004,2024-01-05 10:34:52.195,0.2871,0.0001,0.0,0.0,5.00,0.00,-482.263367,-19.762871,151.791931
2,2024-01-05 10:34:52.228667021,2024-01-05 10:34:52.229,0.2871,0.0001,0.0,0.0,5.00,0.00,-483.006927,-16.474230,151.901566
3,2024-01-05 10:34:52.262000084,2024-01-05 10:34:52.262,0.2871,0.0001,0.0,0.0,5.00,0.00,-480.737061,-17.901360,135.418030
4,2024-01-05 10:34:52.295332909,2024-01-05 10:34:52.295,0.2893,0.0002,0.0,0.0,5.00,0.00,-480.826111,-16.183176,135.999893
5,2024-01-05 10:34:52.328666925,2024-01-05 10:34:52.329,0.2893,0.0002,0.0,0.0,5.00,0.00,-483.828003,-18.554438,152.221420
6,2024-01-05 10:34:52.361999989,2024-01-05 10:34:52.362,0.2893,0.0002,0.0,0.0,5.00,0.00,-480.990173,-16.998444,136.692535
7,2024-01-05 10:34:52.395333052,2024-01-05 10:34:52.395,0.2802,0.0001,0.0,0.0,5.00,0.00,-484.385254,-14.036122,151.920593
8,2024-01-05 10:34:52.428667068,2024-01-05 10:34:52.429,0.2802,0.0001,0.0,0.0,5.00,0.00,-485.242981,-16.541672,151.891312
9,2024-01-05 10:34:52.461999893,2024-01-05 10:34:52.462,0.2802,0.0001,0.0,0.0,5.00,0.00,-483.984833,-14.099407,151.901077
10,2024-01-05 10:34:52.495332956,2024-01-05 10:34:52.495,0.2893,0.0002,0.0,0.0,5.00,0.00,-479.424774,-21.173449,149.269501
11,2024-01-05 10:34:52.528666019,2024-01-05 10:34:52.529,0.2893,0.0002,0.0,0.0,5.00,0.00,-481.546997,-18.046221,151.370453
12,2024-01-05 10:34:52.562000036,2024-01-05 10:34:52.562,0.2893,0.0002,0.0,0.0,5.00,0.00,-483.915009,-19.956011,152.183334
13,2024-01-05 10:34:52.595333099,2024-01-05 10:34:52.595,0.2867,0.0001,0.0,0.0,5.00,0.00,-480.787933,-16.007488,150.681900
14,2024-01-05 10:34:52.628667116,2024-01-05 10:34:52.629,0.2867,0.0001,0.0,0.0,5.00,0.00,-479.334717,-19.394783,148.832230
15,2024-01-05 10:34:52.661999941,2024-01-05 10:34:52.662,0.2867,0.0001,0.0,0.0,5.00,0.00,-479.178955,-20.841766,148.878937
16,2024-01-05 10:34:52.695333004,2024-01-05 10:34:52.695,0.2894,0.0002,0.0,0.0,5.00,0.00,-482.697876,-8.916419,151.036179
17,2024-01-05 10:34:52.728667021,2024-01-05 10:34:52.729,0.2894,0.0002,0.0,0.0,5.00,0.00,-480.949860,-12.984543,150.112503
18,2024-01-05 10:34:52.762000084,2024-01-05 10:34:52.762,0.2894,0.0002,0.0,0.0,5.00,0.00,-483.362823,-11.172759,151.537140
19,2024-01-05 10:34:52.795332909,2024-01-05 10:34:52.795,0.2801,0.0002,0.0,0.0,5.00,0.00,-483.026581,-13.407113,151.657059
20,2024-01-05 10:34:52.828666925,2024-01-05 10:34:52.829,0.2801,0.0002,0.0,0.0,5.00,0.00,-481.483887,-10.652870,150.282669
21,2024-01-05 10:34:52.861999989,2024-01-05 10:34:52.862,0.2801,0.0002,0.0,0.0,5.00,0.00,-484.352753,-7.387171,151.320786
22,2024-01-05 10:34:52.895333052,2024-01-05 10:34:52.895,0.2868,0.0002,0.0,0.0,5.00,0.00,-485.295135,-9.531982,151.330246
23,2024-01-05 10:34:52.928667068,2024-01-05 10:34:52.929,0.2868,0.0002,0.0,0.0,5.00,0.00,-480.614899,-8.478767,148.847656
24,2024-01-05 10:34:52.961999893,2024-01-05 10:34:52.962,0.2868,0.0002,0.0,0.0,5.00,0.00,-479.977631,-12.271223,148.758133
25,2024-01-05 10:34:52.995332956,2024-01-05 10:34:52.995,0.3017,0.0002,0.0,0.0,5.00,0.00,-480.049744,-10.057912,148.179749
26,2024-01-05 10:34:53.028666019,2024-01-05 10:34:53.029,0.3017,0.0002,0.0,0.0,5.00,0.00,-484.224365,-9.284156,151.475906
27,2024-01-05 10:34:53.062000036,2024-01-05 10:34:53.062,0.3017,0.0002,0.0,0.0,5.00,0.00,-484.183289,-13.220000,151.866074
28,2024-01-05 10:34:53.095333099,2024-01-05 10:34:53.095,0.2898,0.0002,0.0,0.0,5.24,0.00,-484.752777,-7.331481,151.300797
29,2024-01-05 10:34:53.128667116,2024-01-05 10:34:53.129,0.2898,0.0002,0.0,0.0,5.24,0.00,-484.360992,-2.103022,150.960052
30,2024-01-05 10:34:53.161999941,2024-01-05 10:34:53.162,0.2898,0.0002,0.0,0.0,5.24,0.00,-482.716156,-2.804450,150.401550
31,2024-01-05 10:34:53.195333004,2024-01-05 10:34:53.195,0.2232,5.0391,0.0,0.0,5.24,0.00,-480.846100,-6.660643,148.953598
32,2024-01-05 10:34:53.228667021,2024-01-05 10:34:53.229,0.2232,5.0391,0.0,0.0,5.24,0.00,-483.282227,-5.357822,150.848511
33,2024-01-05 10:34:53.262000084,2024-01-05 10:34:53.262,0.2232,5.0391,0.0,0.0,5.24,0.00,-485.546875,-5.842466,151.150040
34,2024-01-05 10:34:53.295332909,2024-01-05 10:34:53.295,0.1872,5.0391,0.0,0.1,0.00,0.04,-485.133728,-3.707681,151.113052
35,2024-01-05 10:34:53.328666925,2024-01-05 10:34:53.329,0.1872,5.0391,0.0,0.1,0.00,0.04,-480.745300,-6.283593,148.740219
36,2024-01-05 10:34:53.361999989,2024-01-05 10:34:53.362,0.1872,5.0391,0.0,0.1,0.00,0.04,-481.208649,-1.260259,149.228912
37,2024-01-05 10:34:53.395333052,2024-01-05 10:34:53.395,0.1792,5.0391,0.0,0.1,0.00,0.04,-480.780792,-3.175819,148.492065
38,2024-01-05 10:34:53.428667068,2024-01-05 10:34:53.429,0.1792,5.0391,0.0,0.1,0.00,0.04,-483.743988,-7.070776,151.175186
39,2024-01-05 10:34:53.461999893,2024-01-05 10:34:53.462,0.1792,5.0391,0.0,0.1,0.00,0.04,-482.901428,-0.962274,150.387085
40,2024-01-05 10:34:53.495332956,2024-01-05 10:34:53.495,0.1792,5.0391,0.0,0.1,0.00,0.04,-485.160278,-0.565352,151.048141
41,2024-01-05 10:34:53.528666019,2024-01-05 10:34:53.529,0.1826,5.0391,9020.0,0.1,4.86,0.04,-482.156830,-6.938414,150.407379
42,2024-01-05 10:34:53.562000036,2024-01-05 10:34:53.562,0.1826,5.0391,9020.0,0.1,4.86,0.04,-484.536987,-6.937690,151.282547
43,2024-01-05 10:34:53.595333099,2024-01-05 10:34:53.595,0.1826,5.0391,9020.0,0.1,4.86,0.04,-481.774384,-4.715047,149.827316
44,2024-01-05 10:34:53.628667116,2024-01-05 10:34:53.629,0.1654,5.0392,9020.0,0.1,4.86,0.04,-484.763214,-0.631707,150.986557
45,2024-01-05 10:34:53.661999941,2024-01-05 10:34:53.662,0.1654,5.0392,9020.0,0.1,4.86,0.04,-487.743164,5.352181,152.329575
46,2024-01-05 10:34:53.695333004,2024-01-05 10:34:53.695,0.1654,5.0392,9020.0,0.1,4.86,0.04,-484.998230,1.677782,151.369171
47,2024-01-05 10:34:53.728667021,2024-01-05 10:34:53.729,0.1341,5.0391,9020.0,0.1,4.86,0.04,-483.955811,-0.346606,150.843628
48,2024-01-05 10:34:53.762000084,2024-01-05 10:34:53.762,0.1341,5.0391,9020.0,0.1,4.86,0.04,-489.004669,4.512958,153.485748
49,2024-01-05 10:34:53.795332909,2024-01-05 10:34:53.795,0.1341,5.0391,9020.0,0.1,4.86,0.04,-487.486084,6.033064,157.679810

In [16]:
df.tail(50)

,Timestamp,Datetime,Procada Current,Procada Voltage,Laser Power,Wire Current,Wire Speed,Wire Voltage,X,Y,Z
950,2024-01-05 10:35:23.828666925,2024-01-05 10:35:23.829,0.2752,0.0043,0.0,0.0,0.0,0.0,-419.081146,246.394669,152.975449
951,2024-01-05 10:35:23.861999989,2024-01-05 10:35:23.862,0.2752,0.0043,0.0,0.0,0.0,0.0,-418.041016,248.115417,153.013336
952,2024-01-05 10:35:23.895333052,2024-01-05 10:35:23.895,0.2752,0.0043,0.0,0.0,0.0,0.0,-307.223175,376.942352,154.410522
953,2024-01-05 10:35:23.928667068,2024-01-05 10:35:23.929,0.2752,0.0043,0.0,0.0,0.0,0.0,-318.031097,385.642639,128.519577
954,2024-01-05 10:35:23.961999893,2024-01-05 10:35:23.962,0.2752,0.0043,0.0,0.0,0.0,0.0,-304.707245,377.329926,154.211166
955,2024-01-05 10:35:23.995332956,2024-01-05 10:35:23.995,0.2752,0.0043,0.0,0.0,0.0,0.0,-300.202789,374.981201,150.829865
956,2024-01-05 10:35:24.028666019,2024-01-05 10:35:24.029,0.2752,0.0043,0.0,0.0,0.0,0.0,-319.495239,384.656525,125.975632
957,2024-01-05 10:35:24.062000036,2024-01-05 10:35:24.062,0.2752,0.0043,0.0,0.0,0.0,0.0,-305.560394,379.242737,154.452774
958,2024-01-05 10:35:24.095333099,2024-01-05 10:35:24.095,0.2752,0.0043,0.0,0.0,0.0,0.0,-303.844147,379.458008,154.369537
959,2024-01-05 10:35:24.128667116,2024-01-05 10:35:24.129,0.2752,0.0043,0.0,0.0,0.0,0.0,-322.072357,384.867493,124.109779
960,2024-01-05 10:35:24.161999941,2024-01-05 10:35:24.162,0.2752,0.0043,0.0,0.0,0.0,0.0,-307.830292,375.036133,154.256149
961,2024-01-05 10:35:24.195333004,2024-01-05 10:35:24.195,0.2752,0.0043,0.0,0.0,0.0,0.0,-306.648193,377.703278,154.410095
962,2024-01-05 10:35:24.228667021,2024-01-05 10:35:24.229,0.2752,0.0043,0.0,0.0,0.0,0.0,-416.899506,249.984192,153.052704
963,2024-01-05 10:35:24.262000084,2024-01-05 10:35:24.262,0.2752,0.0043,0.0,0.0,0.0,0.0,-415.779663,251.775330,153.158981
964,2024-01-05 10:35:24.295332909,2024-01-05 10:35:24.295,0.2752,0.0043,0.0,0.0,0.0,0.0,-414.687256,253.531906,153.191788
965,2024-01-05 10:35:24.328666925,2024-01-05 10:35:24.329,0.2752,0.0043,0.0,0.0,0.0,0.0,-301.643188,382.337738,154.508759
966,2024-01-05 10:35:24.361999989,2024-01-05 10:35:24.362,0.2752,0.0043,0.0,0.0,0.0,0.0,-299.526306,384.145630,154.507797
967,2024-01-05 10:35:24.395333052,2024-01-05 10:35:24.395,0.2752,0.0043,0.0,0.0,0.0,0.0,-297.860291,383.870422,154.423019
968,2024-01-05 10:35:24.428667068,2024-01-05 10:35:24.429,0.2752,0.0043,0.0,0.0,0.0,0.0,-297.027222,377.450989,150.975281
969,2024-01-05 10:35:24.461999893,2024-01-05 10:35:24.462,0.2752,0.0043,0.0,0.0,0.0,0.0,-298.458374,384.408051,154.483444
970,2024-01-05 10:35:24.495332956,2024-01-05 10:35:24.495,0.2752,0.0043,0.0,0.0,0.0,0.0,-297.452057,377.231415,151.025253
971,2024-01-05 10:35:24.528666019,2024-01-05 10:35:24.529,0.2752,0.0043,0.0,0.0,0.0,0.0,-303.637787,380.365326,154.461868
972,2024-01-05 10:35:24.562000036,2024-01-05 10:35:24.562,0.2752,0.0043,0.0,0.0,0.0,0.0,-298.791656,384.698883,154.505569
973,2024-01-05 10:35:24.595333099,2024-01-05 10:35:24.595,0.2752,0.0043,0.0,0.0,0.0,0.0,-299.147095,381.978638,154.319839
974,2024-01-05 10:35:24.628667116,2024-01-05 10:35:24.629,0.2752,0.0043,0.0,0.0,0.0,0.0,-302.705536,379.558319,154.317123
975,2024-01-05 10:35:24.661999941,2024-01-05 10:35:24.662,0.2752,0.0043,0.0,0.0,0.0,0.0,-300.935425,380.454987,154.275269
976,2024-01-05 10:35:24.695333004,2024-01-05 10:35:24.695,0.2752,0.0043,0.0,0.0,0.0,0.0,-295.410431,378.480530,150.678375
977,2024-01-05 10:35:24.728667021,2024-01-05 10:35:24.729,0.2752,0.0043,0.0,0.0,0.0,0.0,-413.618469,255.242737,153.200775
978,2024-01-05 10:35:24.762000084,2024-01-05 10:35:24.762,0.2752,0.0043,0.0,0.0,0.0,0.0,-412.505280,257.035431,153.200439
979,2024-01-05 10:35:24.795332909,2024-01-05 10:35:24.795,0.2752,0.0043,0.0,0.0,0.0,0.0,-411.400818,258.783630,153.203888
980,2024-01-05 10:35:24.828666925,2024-01-05 10:35:24.829,0.2752,0.0043,0.0,0.0,0.0,0.0,-410.288239,260.524109,153.206665
981,2024-01-05 10:35:24.861999989,2024-01-05 10:35:24.862,0.2752,0.0043,0.0,0.0,0.0,0.0,-291.718750,387.536041,154.423004
982,2024-01-05 10:35:24.895333052,2024-01-05 10:35:24.895,0.2752,0.0043,0.0,0.0,0.0,0.0,-296.924744,383.631470,154.337845
983,2024-01-05 10:35:24.928667068,2024-01-05 10:35:24.929,0.2752,0.0043,0.0,0.0,0.0,0.0,-296.859772,386.024475,154.598923
984,2024-01-05 10:35:24.961999893,2024-01-05 10:35:24.962,0.2752,0.0043,0.0,0.0,0.0,0.0,-293.434479,386.714905,154.453323
985,2024-01-05 10:35:24.995332956,2024-01-05 10:35:24.995,0.2752,0.0043,0.0,0.0,0.0,0.0,-298.468140,385.005463,154.564835
986,2024-01-05 10:35:25.028666019,2024-01-05 10:35:25.029,0.2752,0.0043,0.0,0.0,0.0,0.0,-295.342804,384.657379,154.328735
987,2024-01-05 10:35:25.062000036,2024-01-05 10:35:25.062,0.2752,0.0043,0.0,0.0,0.0,0.0,-294.235138,388.638367,154.474640
988,2024-01-05 10:35:25.095333099,2024-01-05 10:35:25.095,0.2752,0.0043,0.0,0.0,0.0,0.0,-294.957245,387.460052,154.614838
989,2024-01-05 10:35:25.128667116,2024-01-05 10:35:25.129,0.2752,0.0043,0.0,0.0,0.0,0.0,-293.552582,388.036835,154.603836
990,2024-01-05 10:35:25.161999941,2024-01-05 10:35:25.162,0.2752,0.0043,0.0,0.0,0.0,0.0,-409.172089,262.261902,153.208450
991,2024-01-05 10:35:25.195333004,2024-01-05 10:35:25.195,0.2752,0.0043,0.0,0.0,0.0,0.0,-407.986328,264.093323,153.208740
992,2024-01-05 10:35:25.228667021,2024-01-05 10:35:25.229,0.2752,0.0043,0.0,0.0,0.0,0.0,-406.844391,265.862244,153.187149
993,2024-01-05 10:35:25.262000084,2024-01-05 10:35:25.262,0.2752,0.0043,0.0,0.0,0.0,0.0,-291.761841,388.193909,154.548309
994,2024-01-05 10:35:25.295332909,2024-01-05 10:35:25.295,0.2752,0.0043,0.0,0.0,0.0,0.0,-289.993073,388.418976,154.383942
995,2024-01-05 10:35:25.328666925,2024-01-05 10:35:25.329,0.2752,0.0043,0.0,0.0,0.0,0.0,-288.154022,393.276672,154.550507
996,2024-01-05 10:35:25.361999989,2024-01-05 10:35:25.362,0.2752,0.0043,0.0,0.0,0.0,0.0,-287.799164,391.751678,154.587921
997,2024-01-05 10:35:25.395333052,2024-01-05 10:35:25.395,0.2752,0.0043,0.0,0.0,0.0,0.0,-286.253357,390.935303,154.363449
998,2024-01-05 10:35:25.428667068,2024-01-05 10:35:25.429,0.2752,0.0043,0.0,0.0,0.0,0.0,-289.399170,392.017395,154.625916
999,2024-01-05 10:35:25.461999893,2024-01-05 10:35:25.462,0.2752,0.0043,0.0,0.0,0.0,0.0,-291.027283,390.028168,154.691437

In [17]:
print("Basic statistics:\n")

df.describe()

Basic statistics:

,Timestamp,Datetime,Procada Current,Procada Voltage,Laser Power,Wire Current,Wire Speed,Wire Voltage,X,Y,Z
count,1000,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2024-01-05 10:35:08.812000,2024-01-05 10:35:08.812000,28.965345,1.765583,3829.398000,0.044600,2.461910,0.017840,-430.759930,180.087668,151.534939
min,2024-01-05 10:34:52.161999941,2024-01-05 10:34:52.162000,0.134100,0.000100,0.000000,0.000000,0.000000,0.000000,-491.213104,-21.173449,96.233009
25%,2024-01-05 10:35:00.486999552,2024-01-05 10:35:00.486749952,0.275200,0.004300,0.000000,0.000000,0.000000,0.000000,-476.894089,81.326271,151.504318
50%,2024-01-05 10:35:08.811999744,2024-01-05 10:35:08.812000,0.275200,0.004300,0.000000,0.000000,0.000000,0.000000,-453.475479,170.617676,152.867928
75%,2024-01-05 10:35:17.137000448,2024-01-05 10:35:17.137250048,71.136600,3.863300,9020.000000,0.100000,5.240000,0.040000,-398.811897,278.328461,153.751873
max,2024-01-05 10:35:25.461999893,2024-01-05 10:35:25.462000,76.389700,5.039200,9020.000000,0.100000,5.240000,0.040000,-286.253357,393.276672,157.679810
std,NaN,NaN,35.023862,1.989290,4420.988124,0.049732,2.600706,0.019893,55.500686,118.575226,6.431179

In [18]:
file_path = cleaned_dir/"cleaned_proc_data_v1.csv"
df.to_csv(file_path, index = False)

In [19]:
file_path = cleaned_dir/"cleaned_proc_data_v1.xlsx"

df.to_excel(file_path, index = False)